# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c37a5fca50f6f8141c8aa57aee23aeb5b3a321dd9d6b9ca7a6b5e01d242260de45e5636ef6871c896b22302f9143592a86f4af850f4a38c2a498b2056d54ad6a

test:
  secret_key_base: f6ce1dca606a6eff8354110fbbd365845404ed586a5be0db6c9f4205d18f5bdaba7494930b1beb685b84655b3106e2732a9ddd5602c11ee81d1e7d69d0207067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
